name: healthbuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.4.0
  crypto: ^3.0.3
  dio: ^5.9.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  pedometer: ^4.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  swipable_stack: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assests/login_logo.png"

flutter_native_splash:
  color: "#0A1B3D"
  background_image: assests/login_logo.png
  android_12:
    image: assests/login_logo.png
  android: true
  fullscreen: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assests/